spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: ERROR